"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";

import { NAV_ITEMS } from "@/components/layout/nav-config";
import {
  filterNavItems,
  isNavItemActive,
} from "@/components/layout/nav-filter";
import {
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupContent,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarRail,
} from "@/components/ui/sidebar";
import { usePermissions } from "@/features/auth/hooks/use-permissions";

/**
 * Permanent CRM sidebar — thin renderer over nav-config.
 * Future modules: extend nav-config only; do not edit this file for routine adds.
 */
export function AppSidebar() {
  const { can, canAny } = usePermissions();
  const pathname = usePathname();
  const visibleNav = filterNavItems(NAV_ITEMS, can, canAny);

  return (
    <Sidebar collapsible="icon">
      <SidebarHeader className="border-b border-sidebar-border">
        <SidebarMenu>
          <SidebarMenuItem>
            <SidebarMenuButton
              size="lg"
              render={<Link href="/" />}
              tooltip="Clinexa"
            >
              <span className="flex size-8 items-center justify-center rounded-md bg-sidebar-primary text-sm font-semibold text-sidebar-primary-foreground">
                C
              </span>
              <span className="truncate font-semibold tracking-tight">
                Clinexa
              </span>
            </SidebarMenuButton>
          </SidebarMenuItem>
        </SidebarMenu>
      </SidebarHeader>
      <SidebarContent>
        <SidebarGroup>
          <SidebarGroupContent>
            <SidebarMenu>
              {visibleNav.map((item) => {
                const Icon = item.icon;
                const active = isNavItemActive(pathname, item.route);
                return (
                  <SidebarMenuItem key={item.route}>
                    <SidebarMenuButton
                      isActive={active}
                      tooltip={item.title}
                      disabled={item.disabled}
                      render={<Link href={item.route} />}
                    >
                      <Icon />
                      <span>{item.title}</span>
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                );
              })}
            </SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>
      </SidebarContent>
      <SidebarRail />
    </Sidebar>
  );
}
