/**
 * Permission codes PERM-<MOD>-### (docs/08 dictionary). Single source of truth.
 * Do not use raw permission string literals outside this module.
 */
export const Permissions = {
  AUTH_REGISTER: 'PERM-AUTH-001',
  AUTH_SIGN_IN: 'PERM-AUTH-002',
  AUTH_PASSWORD_RESET: 'PERM-AUTH-003',
  AUTH_SESSION_END: 'PERM-AUTH-004',
  /** System capability — not assigned to users. */
  AUTH_ENFORCE_RBAC: 'PERM-AUTH-005',

  SRCH_CRM: 'PERM-SRCH-002',

  CRM_PATIENT_RECORDS: 'PERM-CRM-010',
  CRM_CONSULT_QUEUE: 'PERM-CRM-001',
  CRM_APPROVE_RX: 'PERM-CRM-002',
  CRM_DECLINE_RX: 'PERM-CRM-003',
  CRM_REQUEST_INFO: 'PERM-CRM-004',
  CRM_CLINICAL_NOTES: 'PERM-CRM-005',
  CRM_PHARMACY_REVIEW: 'PERM-CRM-006',
  CRM_PHARMACY_READY: 'PERM-CRM-007',
  CRM_ACCESS_SHELL: 'PERM-CRM-020',
  /** Guardian administrative context shell (`/guardian/*`). */
  GRD_ACCESS_SHELL: 'PERM-GRD-001',

  PRT_VIEW_OWN_PROFILE: 'PERM-PRT-001',
  PRT_UPDATE_OWN_PROFILE: 'PERM-PRT-002',
  PRT_DASHBOARD: 'PERM-PRT-010',

  PRD_VIEW_PUBLISHED: 'PERM-PRD-001',
  PRD_MANAGE: 'PERM-PRD-002',

  CAT_VIEW_PUBLISHED: 'PERM-CAT-001',
  CAT_MANAGE: 'PERM-CAT-002',

  CART_MANAGE_LINES: 'PERM-CART-001',
  CART_STAGE_COUPON: 'PERM-CART-002',

  CHK_START: 'PERM-CHK-001',
  CHK_FINALIZE: 'PERM-CHK-002',

  PAY_PAY: 'PERM-PAY-001',
  PAY_MANAGE_METHODS: 'PERM-PAY-002',
  PAY_INITIATE_REFUND: 'PERM-PAY-003',

  ORD_VIEW: 'PERM-ORD-001',
  ORD_CANCEL: 'PERM-ORD-002',
  ORD_FULFILL: 'PERM-ORD-003',

  SUB_MANAGE_OWN: 'PERM-SUB-001',
  SUB_CONFIGURE_PLANS: 'PERM-SUB-002',
  SUB_ASSIST_RENEWAL: 'PERM-SUB-003',

  QST_SUBMIT: 'PERM-QST-001',
  QST_VIEW_OWN_STATUS: 'PERM-QST-002',
  QST_VIEW_FULL_ANSWERS: 'PERM-QST-003',
  QST_CONFIGURE: 'PERM-QST-004',

  APT_OWN: 'PERM-APT-001',
  APT_STAFF_MANAGE: 'PERM-APT-002',

  DOC_OWN: 'PERM-DOC-001',
  DOC_STAFF: 'PERM-DOC-002',
  DOC_AUDIT_PHI: 'PERM-DOC-003',

  NTF_RECEIVE: 'PERM-NTF-001',
  NTF_MANAGE_PREFS: 'PERM-NTF-002',
  NTF_MANAGE_TEMPLATES: 'PERM-NTF-003',

  INV_VIEW: 'PERM-INV-001',
  INV_ADJUST: 'PERM-INV-002',
  INV_LOW_STOCK: 'PERM-INV-003',

  RPT_VIEW: 'PERM-RPT-001',
  RPT_EXPORT: 'PERM-RPT-002',

  ANL_MARKETING: 'PERM-ANL-001',
  ANL_OPS_CLINICAL: 'PERM-ANL-002',

  CMS_MANAGE: 'PERM-CMS-001',
  CMS_PUBLISH: 'PERM-CMS-002',

  BLG_MANAGE: 'PERM-BLG-001',

  CPN_CONFIGURE: 'PERM-CPN-001',
  CPN_REDEEM: 'PERM-CPN-002',

  SUP_CREATE_TICKET: 'PERM-SUP-001',
  SUP_TRIAGE: 'PERM-SUP-002',
  SUP_LINK_TICKET: 'PERM-SUP-003',

  ADM_MANAGE_USERS: 'PERM-ADM-001',
  ADM_ASSIGN_ROLES: 'PERM-ADM-002',
  ADM_CONFIGURE_WORKFLOWS: 'PERM-ADM-003',
  ADM_VIEW_AUDIT: 'PERM-ADM-010',
  ADM_ACCESS_ADMINISTRATION: 'PERM-ADM-020',

  SET_MANAGE: 'PERM-SET-001',
  SET_OVERSELL_POLICIES: 'PERM-SET-002',

  REV_SUBMIT: 'PERM-REV-001',
  REV_MODERATE: 'PERM-REV-002',
} as const;

export type PermissionCode = (typeof Permissions)[keyof typeof Permissions];

export type PermissionDefinition = {
  code: PermissionCode;
  module: string;
  name: string;
  description: string;
  resource?: string;
  action?: string;
};

/** Full dictionary for seeding (docs/08 §4). Includes system-only AUTH_ENFORCE_RBAC. */
export const PERMISSION_DEFINITIONS: readonly PermissionDefinition[] = [
  {
    code: Permissions.AUTH_REGISTER,
    module: 'AUTH',
    name: 'Register',
    description: 'Create a patient account via Store registration.',
    resource: 'auth',
    action: 'register',
  },
  {
    code: Permissions.AUTH_SIGN_IN,
    module: 'AUTH',
    name: 'Sign-in',
    description: 'Authenticate with email/password and establish a session.',
    resource: 'auth',
    action: 'sign_in',
  },
  {
    code: Permissions.AUTH_PASSWORD_RESET,
    module: 'AUTH',
    name: 'Password reset',
    description: 'Initiate and complete password reset.',
    resource: 'auth',
    action: 'password_reset',
  },
  {
    code: Permissions.AUTH_SESSION_END,
    module: 'AUTH',
    name: 'Session end',
    description: 'Sign out and invalidate the current session.',
    resource: 'auth',
    action: 'session_end',
  },
  {
    code: Permissions.AUTH_ENFORCE_RBAC,
    module: 'AUTH',
    name: 'Enforce RBAC (system)',
    description: 'Platform server-side RBAC evaluation (not user-granted).',
    resource: 'auth',
    action: 'enforce_rbac',
  },
  {
    code: Permissions.SRCH_CRM,
    module: 'SRCH',
    name: 'CRM search',
    description: 'Search patients, orders, and catalog within CRM.',
    resource: 'search',
    action: 'crm',
  },
  {
    code: Permissions.CRM_PATIENT_RECORDS,
    module: 'CRM',
    name: 'Search/view patient records',
    description: 'View patient account records in CRM (scoped).',
    resource: 'crm',
    action: 'patient_records',
  },
  {
    code: Permissions.CRM_CONSULT_QUEUE,
    module: 'CRM',
    name: 'Open consult queue',
    description: 'Access the clinical consult queue.',
    resource: 'crm',
    action: 'consult_queue',
  },
  {
    code: Permissions.CRM_APPROVE_RX,
    module: 'CRM',
    name: 'Approve prescription',
    description: 'Clinically approve a prescription / treatment decision.',
    resource: 'crm',
    action: 'approve_rx',
  },
  {
    code: Permissions.CRM_DECLINE_RX,
    module: 'CRM',
    name: 'Decline prescription',
    description: 'Clinically decline a prescription / treatment decision.',
    resource: 'crm',
    action: 'decline_rx',
  },
  {
    code: Permissions.CRM_REQUEST_INFO,
    module: 'CRM',
    name: 'Request additional info',
    description: 'Request supplemental intake for a consult case.',
    resource: 'crm',
    action: 'request_info',
  },
  {
    code: Permissions.CRM_CLINICAL_NOTES,
    module: 'CRM',
    name: 'Clinical notes',
    description: 'Create and update clinical notes on a consult case.',
    resource: 'crm',
    action: 'clinical_notes',
  },
  {
    code: Permissions.CRM_PHARMACY_REVIEW,
    module: 'CRM',
    name: 'Pharmacy review',
    description: 'Perform pharmacy review of approved prescriptions.',
    resource: 'crm',
    action: 'pharmacy_review',
  },
  {
    code: Permissions.CRM_PHARMACY_READY,
    module: 'CRM',
    name: 'Mark pharmacy ready / flag',
    description: 'Mark pharmacy readiness or flag issues.',
    resource: 'crm',
    action: 'pharmacy_ready',
  },
  {
    code: Permissions.CRM_ACCESS_SHELL,
    module: 'CRM',
    name: 'Access CRM shell',
    description: 'Enter the CRM operational context shell (`/crm/*`).',
    resource: 'crm',
    action: 'access_shell',
  },
  {
    code: Permissions.GRD_ACCESS_SHELL,
    module: 'GRD',
    name: 'Access Guardian context',
    description:
      'Enter the Guardian administrative context shell (`/guardian/*`).',
    resource: 'guardian',
    action: 'access_shell',
  },
  {
    code: Permissions.PRT_VIEW_OWN_PROFILE,
    module: 'PRT',
    name: 'View own profile',
    description: 'Read the authenticated patient’s own profile.',
    resource: 'portal',
    action: 'view_profile',
  },
  {
    code: Permissions.PRT_UPDATE_OWN_PROFILE,
    module: 'PRT',
    name: 'Update own profile',
    description: 'Update the authenticated patient’s own profile.',
    resource: 'portal',
    action: 'update_profile',
  },
  {
    code: Permissions.PRT_DASHBOARD,
    module: 'PRT',
    name: 'Patient Portal dashboard',
    description: 'Access the Portal self-service aggregate.',
    resource: 'portal',
    action: 'dashboard',
  },
  {
    code: Permissions.PRD_VIEW_PUBLISHED,
    module: 'PRD',
    name: 'View published products',
    description: 'Read published product catalog on the Store.',
    resource: 'product',
    action: 'view_published',
  },
  {
    code: Permissions.PRD_MANAGE,
    module: 'PRD',
    name: 'Manage/publish products',
    description: 'Create, update, publish, archive products in CRM.',
    resource: 'product',
    action: 'manage',
  },
  {
    code: Permissions.CAT_VIEW_PUBLISHED,
    module: 'CAT',
    name: 'View published categories',
    description: 'Read published category pages on the Store.',
    resource: 'category',
    action: 'view_published',
  },
  {
    code: Permissions.CAT_MANAGE,
    module: 'CAT',
    name: 'Manage categories',
    description: 'Create, update, publish category structure in CRM.',
    resource: 'category',
    action: 'manage',
  },
  {
    code: Permissions.CART_MANAGE_LINES,
    module: 'CART',
    name: 'Manage cart lines',
    description: 'Create, update, and delete cart line items.',
    resource: 'cart',
    action: 'manage_lines',
  },
  {
    code: Permissions.CART_STAGE_COUPON,
    module: 'CART',
    name: 'Stage coupon on cart',
    description: 'Apply or clear a coupon code on the cart.',
    resource: 'cart',
    action: 'stage_coupon',
  },
  {
    code: Permissions.CHK_START,
    module: 'CHK',
    name: 'Start checkout',
    description: 'Begin checkout from a staged cart.',
    resource: 'checkout',
    action: 'start',
  },
  {
    code: Permissions.CHK_FINALIZE,
    module: 'CHK',
    name: 'Finalize order',
    description: 'Complete checkout and create an order.',
    resource: 'checkout',
    action: 'finalize',
  },
  {
    code: Permissions.PAY_PAY,
    module: 'PAY',
    name: 'Pay',
    description: 'Submit payment for checkout or renewal via PSP.',
    resource: 'payment',
    action: 'pay',
  },
  {
    code: Permissions.PAY_MANAGE_METHODS,
    module: 'PAY',
    name: 'Manage own payment methods',
    description: 'View/update saved payment methods for the owning patient.',
    resource: 'payment',
    action: 'manage_methods',
  },
  {
    code: Permissions.PAY_INITIATE_REFUND,
    module: 'PAY',
    name: 'Initiate refund',
    description: 'Start a staff- or policy-allowed refund.',
    resource: 'payment',
    action: 'initiate_refund',
  },
  {
    code: Permissions.ORD_VIEW,
    module: 'ORD',
    name: 'View orders',
    description: 'View order records within role scope.',
    resource: 'order',
    action: 'view',
  },
  {
    code: Permissions.ORD_CANCEL,
    module: 'ORD',
    name: 'Cancel order',
    description: 'Cancel an order when policy allows.',
    resource: 'order',
    action: 'cancel',
  },
  {
    code: Permissions.ORD_FULFILL,
    module: 'ORD',
    name: 'Fulfill/ship order',
    description: 'Record fulfillment after clinical and pharmacy gates.',
    resource: 'order',
    action: 'fulfill',
  },
  {
    code: Permissions.SUB_MANAGE_OWN,
    module: 'SUB',
    name: 'Manage own subscription',
    description: 'View, update, and cancel subscriptions (scoped).',
    resource: 'subscription',
    action: 'manage_own',
  },
  {
    code: Permissions.SUB_CONFIGURE_PLANS,
    module: 'SUB',
    name: 'Configure subscription plans',
    description: 'Create and publish subscription plan configuration.',
    resource: 'subscription',
    action: 'configure_plans',
  },
  {
    code: Permissions.SUB_ASSIST_RENEWAL,
    module: 'SUB',
    name: 'Assist renewal',
    description: 'Assist with renewal failures without bypassing gates.',
    resource: 'subscription',
    action: 'assist_renewal',
  },
  {
    code: Permissions.QST_SUBMIT,
    module: 'QST',
    name: 'Submit questionnaire responses',
    description: 'Complete intake questionnaire answers.',
    resource: 'questionnaire',
    action: 'submit',
  },
  {
    code: Permissions.QST_VIEW_OWN_STATUS,
    module: 'QST',
    name: 'View own questionnaire status',
    description: 'View status of own questionnaire submissions.',
    resource: 'questionnaire',
    action: 'view_own_status',
  },
  {
    code: Permissions.QST_VIEW_FULL_ANSWERS,
    module: 'QST',
    name: 'View full questionnaire answers',
    description: 'Read full clinical questionnaire answer sets.',
    resource: 'questionnaire',
    action: 'view_full_answers',
  },
  {
    code: Permissions.QST_CONFIGURE,
    module: 'QST',
    name: 'Configure questionnaire definitions',
    description: 'Create, version, and bind questionnaire definitions.',
    resource: 'questionnaire',
    action: 'configure',
  },
  {
    code: Permissions.APT_OWN,
    module: 'APT',
    name: 'Book/cancel own appointments',
    description: 'Manage the patient’s own appointments.',
    resource: 'appointment',
    action: 'own',
  },
  {
    code: Permissions.APT_STAFF_MANAGE,
    module: 'APT',
    name: 'Staff manage appointments',
    description: 'View and manage appointments in CRM.',
    resource: 'appointment',
    action: 'staff_manage',
  },
  {
    code: Permissions.DOC_OWN,
    module: 'DOC',
    name: 'View/download own documents',
    description: 'View and download the patient’s own documents.',
    resource: 'document',
    action: 'own',
  },
  {
    code: Permissions.DOC_STAFF,
    module: 'DOC',
    name: 'Staff attach/view documents',
    description: 'Attach or view documents in case/ticket/order context.',
    resource: 'document',
    action: 'staff',
  },
  {
    code: Permissions.DOC_AUDIT_PHI,
    module: 'DOC',
    name: 'Audit PHI document access',
    description: 'Support audit of PHI document view/download events.',
    resource: 'document',
    action: 'audit_phi',
  },
  {
    code: Permissions.NTF_RECEIVE,
    module: 'NTF',
    name: 'Receive notifications',
    description: 'Receive domain-triggered notifications.',
    resource: 'notification',
    action: 'receive',
  },
  {
    code: Permissions.NTF_MANAGE_PREFS,
    module: 'NTF',
    name: 'Manage notification preferences',
    description: 'Update non-mandatory notification preferences for self.',
    resource: 'notification',
    action: 'manage_prefs',
  },
  {
    code: Permissions.NTF_MANAGE_TEMPLATES,
    module: 'NTF',
    name: 'Manage notification templates',
    description: 'Configure notification templates used by the platform.',
    resource: 'notification',
    action: 'manage_templates',
  },
  {
    code: Permissions.INV_VIEW,
    module: 'INV',
    name: 'View inventory',
    description: 'View stock levels and inventory status.',
    resource: 'inventory',
    action: 'view',
  },
  {
    code: Permissions.INV_ADJUST,
    module: 'INV',
    name: 'Adjust/reserve/decrement inventory',
    description: 'Reserve, decrement, or adjust inventory.',
    resource: 'inventory',
    action: 'adjust',
  },
  {
    code: Permissions.INV_LOW_STOCK,
    module: 'INV',
    name: 'Low-stock alerts',
    description: 'Receive and act on low-stock operational alerts.',
    resource: 'inventory',
    action: 'low_stock',
  },
  {
    code: Permissions.RPT_VIEW,
    module: 'RPT',
    name: 'View reports',
    description: 'View operational/clinical tabular reports within RBAC.',
    resource: 'report',
    action: 'view',
  },
  {
    code: Permissions.RPT_EXPORT,
    module: 'RPT',
    name: 'Export reports',
    description: 'Export authorized reports.',
    resource: 'report',
    action: 'export',
  },
  {
    code: Permissions.ANL_MARKETING,
    module: 'ANL',
    name: 'Marketing-safe analytics',
    description: 'View funnel/marketing analytics excluding unnecessary PHI.',
    resource: 'analytics',
    action: 'marketing',
  },
  {
    code: Permissions.ANL_OPS_CLINICAL,
    module: 'ANL',
    name: 'Ops/clinical analytics',
    description: 'View operational and clinical queue/metrics dashboards.',
    resource: 'analytics',
    action: 'ops_clinical',
  },
  {
    code: Permissions.CMS_MANAGE,
    module: 'CMS',
    name: 'Manage CMS content',
    description: 'Create and edit CMS pages, banners, FAQs, and blocks.',
    resource: 'cms',
    action: 'manage',
  },
  {
    code: Permissions.CMS_PUBLISH,
    module: 'CMS',
    name: 'Publish CMS content',
    description: 'Publish or unpublish CMS content to the Store.',
    resource: 'cms',
    action: 'publish',
  },
  {
    code: Permissions.BLG_MANAGE,
    module: 'BLG',
    name: 'Manage blogs',
    description: 'Create, edit, publish, and archive blog posts.',
    resource: 'blog',
    action: 'manage',
  },
  {
    code: Permissions.CPN_CONFIGURE,
    module: 'CPN',
    name: 'Configure coupons',
    description: 'Create, update, and archive promotional coupons.',
    resource: 'coupon',
    action: 'configure',
  },
  {
    code: Permissions.CPN_REDEEM,
    module: 'CPN',
    name: 'Redeem coupon',
    description: 'Apply a valid coupon at checkout.',
    resource: 'coupon',
    action: 'redeem',
  },
  {
    code: Permissions.SUP_CREATE_TICKET,
    module: 'SUP',
    name: 'Create support ticket',
    description: 'Create a support ticket from the Patient Portal.',
    resource: 'support',
    action: 'create_ticket',
  },
  {
    code: Permissions.SUP_TRIAGE,
    module: 'SUP',
    name: 'Triage/resolve tickets',
    description: 'Triage and resolve support tickets in CRM.',
    resource: 'support',
    action: 'triage',
  },
  {
    code: Permissions.SUP_LINK_TICKET,
    module: 'SUP',
    name: 'Link ticket to order/patient',
    description: 'Associate tickets with patient and order records.',
    resource: 'support',
    action: 'link_ticket',
  },
  {
    code: Permissions.ADM_MANAGE_USERS,
    module: 'ADM',
    name: 'Manage users',
    description: 'Create and update staff/patient user records.',
    resource: 'admin',
    action: 'manage_users',
  },
  {
    code: Permissions.ADM_ASSIGN_ROLES,
    module: 'ADM',
    name: 'Assign roles',
    description: 'Assign and change roles/permissions.',
    resource: 'admin',
    action: 'assign_roles',
  },
  {
    code: Permissions.ADM_CONFIGURE_WORKFLOWS,
    module: 'ADM',
    name: 'Configure workflows',
    description: 'Configure catalog, questionnaires, and consult workflows.',
    resource: 'admin',
    action: 'configure_workflows',
  },
  {
    code: Permissions.ADM_VIEW_AUDIT,
    module: 'ADM',
    name: 'View audit logs',
    description: 'Read clinical/admin audit log records.',
    resource: 'admin',
    action: 'view_audit',
  },
  {
    code: Permissions.ADM_ACCESS_ADMINISTRATION,
    module: 'ADM',
    name: 'Access Administration',
    description:
      'Access the CRM Administration plane (platform governance console).',
    resource: 'admin',
    action: 'access_administration',
  },
  {
    code: Permissions.SET_MANAGE,
    module: 'SET',
    name: 'Manage platform settings',
    description: 'Create/update platform configuration settings.',
    resource: 'settings',
    action: 'manage',
  },
  {
    code: Permissions.SET_OVERSELL_POLICIES,
    module: 'SET',
    name: 'Manage oversell/publish policies',
    description: 'Configure oversell and publish-safety policies.',
    resource: 'settings',
    action: 'oversell_policies',
  },
  {
    code: Permissions.REV_SUBMIT,
    module: 'REV',
    name: 'Submit product review',
    description: 'Submit an eligible product review.',
    resource: 'review',
    action: 'submit',
  },
  {
    code: Permissions.REV_MODERATE,
    module: 'REV',
    name: 'Moderate reviews',
    description: 'Approve or reject product reviews before public display.',
    resource: 'review',
    action: 'moderate',
  },
] as const;
